// Research projects (most recent first)
export const researchProjects = [
    {
        title: "Climate Change, Language Vulnerability, and Culture Death",
        description:
            "A critical case study examining the impact of climate change on linguistic diversity and cultural preservation in the Eastern coastal region of India under warming scenarios.",
        sponsor: "Indian Institute of Technology Madras, Chennai",
        year: "2024-2027",
    },
    {
        title: "Skilling the Unskilled and the Less Skilled",
        description:
            "A comprehensive need analysis study focusing on skill development requirements in the context of Odisha, examining linguistic and cognitive barriers to effective training programs.",
        sponsor: "Aspire Infolabs, Hyderabad",
        year: "2024-2025",
    },
    {
        title: "Navigating Grammatical Voice to Explore Communication Strategies",
        description:
            "A cross-linguistic study of select Indo-Aryan and Dravidian languages examining how grammatical voice systems facilitate different communication strategies across diverse linguistic communities.",
        sponsor: "Indian Council of Social Science Research (ICSSR), New Delhi",
        year: "2023-2026",
    },
    {
        title: "Detection & Quantification of Gender Bias in Official Text",
        description:
            "An innovative study examining gender bias in academic and official communications within the Indian academic setting using computational linguistics and corpus analysis methods.",
        sponsor: "American Express",
        year: "2023",
    },
    {
        title: "Copula Constructions in Indo-Aryan Languages",
        description:
            "A detailed investigation of copula constructions from typological and discourse pragmatic perspectives, focusing on variation patterns across Indo-Aryan language families.",
        sponsor: "Indian Institute of Technology Madras, Chennai",
        year: "2022-2025",
    },
    {
        title: "Morphosyntax and Discourse Pragmatics",
        description:
            "An extensive study of linguistic constructions in South Asian languages, examining the interface between morphosyntactic structures and discourse-pragmatic functions.",
        sponsor: "Indian Institute of Technology Madras, Chennai",
        year: "2021-2024",
    },
]

// Publications (most recent first)
export const publications = [
    {
        title: "Versatile copulas and their stance-marking uses in conversational Odia, an Indo-Aryan language",
        authors: ["Yap F. H.", "Sahoo A."],
        journal: "Lingua",
        volume: "297",
        year: "2024",
        link: "https://tech-talk.iitm.ac.in/treading-the-territories-of-copulas/",
    },
    {
        title: "From Pixels to Prepositions: Linking Visual Perception with Spatial Prepositions Far and Near",
        authors: ["Raj S. R. K.", "Chakravarthy V. S.", "Sahoo A."],
        journal: "Cognitive Computation",
        year: "2024",
        doi: "10.1007/s12559-024-10329-6",
    },
    {
        title: "Evoking Emotions and Eliciting Heart-Felt Responses through Exclamatives: Unravelling the Potential of 'aiyyoo' in the English Language",
        authors: ["George R.", "Sahoo A."],
        journal: "English Linguistics Research",
        volume: "13(1)",
        year: "2024",
    },
    {
        title: "Non-Active Voices in South Asian Languages",
        authors: ["Chandra P.", "Kaur G.", "Sahoo A."],
        journal: "Passives Cross-Linguistically",
        publisher: "Leiden: Brill",
        year: "2021",
    },
    {
        title: "Ditransitive Active-passives in Malayalam: A brief note",
        authors: ["Chandra P.", "Sahoo A."],
        journal: "International Journal of Dravidian Linguistics",
        volume: "44(1)",
        year: "2015",
        publisher: "Dravidian Linguistics Association",
    },
    {
        title: "Learning Puzzles with Indian English Tags",
        authors: ["Chandra P.", "Sahoo A."],
        journal: "Language and Language Teaching",
        volume: "3(2)",
        year: "2014",
        publisher: "Azim Premji University and Vidya Bhavan Society",
    },
    {
        title: "Passives in South Asian Languages: Some Typological Puzzles",
        authors: ["Chandra P.", "Sahoo A."],
        journal: "Acta Linguistica Asiatica",
        volume: "3(1)",
        year: "2013",
        publisher: "University of Ljubljana, Slovenia",
    },
    {
        title: "Odia passives with ditransitives",
        authors: ["Sahoo A."],
        journal: "LAEL-5 PG Conference Proceedings",
        year: "2010",
        publisher: "Lancaster University, Lancaster, UK",
    },
    {
        title: "Gradience In ditransitives and morphological specifities: The case Of Oriya",
        authors: ["Chandra P.", "Sahoo A."],
        journal: "AICL-32 Conference Proceedings",
        year: "2010",
        publisher: "Linguistic Society of India",
    },
    {
        title: "Yes-no Questions: Probing the Structures of Indian English",
        authors: ["Sahoo A.", "Chandra P."],
        journal: "31st All India Conference of Linguistics",
        year: "2009",
        publisher: "Hyderabad Central University",
    },
]

// Conferences (most recent first)
export const conferences = [
    {
        title: "Definiteness marking and de-honorification in Odia, an eastern Indo-Aryan language",
        authors: ["Foong Ha Yap", "Anindita Sahoo"],
        conference: "Annual Research Forum",
        organizer: null,
        location: "Hong Kong",
        date: "8th Dec 2024",
    },
    {
        title: "From linking verb to auxiliation and focus marking: On the versatile uses of copulas in Malayalam, a Dravidian language",
        authors: ["Anindita Sahoo", "Foong Ha Yap", "Akshay Raj"],
        conference: "15th International Conference of Association for Linguistic Typology",
        organizer: "NTU Singapore",
        location: "Singapore",
        date: "4th to 6th Dec 2024",
    },
    {
        title: "On the intransitivizing uses of kon/kol in Dravidian languages",
        authors: ["Gunti Prem Sagar", "Anindita Sahoo", "Foong Ha Yap"],
        conference: "15th International Conference of Association for Linguistic Typology",
        organizer: "NTU Singapore",
        location: "Singapore",
        date: "4th to 6th Dec 2024",
    },
    {
        title: "On the extended uses of paD ‘fall’ and its cognates as voice markers in Dravidian languages",
        authors: ["Anindita Sahoo", "Foong Ha Yap", "Gunti Prem Sagar"],
        conference: "57th Annual Meeting of the Societas Linguistica Europaea",
        organizer: "University of Helsinki",
        location: "Helsinki, Finland",
        date: "21st to 25th Aug 2024",
    },
    {
        title: "Light verbs and their role in grammatical voice constructions in eastern Indo-Aryan languages",
        authors: ["Snigdha Medhi", "Anindita Sahoo", "Foong Ha Yap"],
        conference: "57th Annual Meeting of Societas Linguistica Europaea",
        organizer: "University of Helsinki",
        location: "Helsinki, Finland",
        date: "21st to 25th Aug 2024",
    },
    {
        title: "Effects of degree of permanence on inversion: Some insights from copula constructions in eastern Indo-Aryan languages",
        authors: ["Anindita Sahoo", "Foong Ha Yap", "Snigdha Medhi", "Pratiti Palit"],
        conference: "56th Annual Meeting of the Societas Linguistica Europaea",
        organizer: "National and Kapodistrian University of Athens",
        location: "Athens, Greece",
        date: "29th Aug to 1st Sep 2023",
    },
    {
        title: "De-honorification strategies in Odia: an interactional linguistics perspective",
        authors: ["Anindita Sahoo", "Foong Ha Yap"],
        conference: "56th Annual Meeting of the Societas Linguistica Europaea",
        organizer: "National and Kapodistrian University of Athens",
        location: "Athens, Greece",
        date: "29th Aug to 1st Sep 2023",
    },
    {
        title: "Beyond the dichotomy of Standard vs Non-Standard: A Sociolinguistic Study on the features 'Standard Language' formation in Malayalam",
        authors: ["Vishnu Suresh", "Anindita Sahoo"],
        conference: "6th Asian Junior Linguists Conference",
        organizer: "Sogang University",
        location: "Seoul, Korea",
        date: "10th to 11th Dec 2021",
    },
    {
        title: "Dyslexia: An Analysis of Syntactic Errors",
        authors: ["Anindita Sahoo", "Priyanka Mowlali"],
        conference: "2nd Malaysian Association of Applied Linguistics Conference",
        organizer: null,
        location: "Malaysia",
        date: "8th to 10th Sep 2021",
    },
    {
        title: "On the de-h honorification function of copula 'achhi' in Odia: A stance Triangle Analysis",
        authors: ["Anindita Sahoo"],
        conference: "17th International Pragmatics Conference",
        organizer: "Zurich University of Applied Sciences",
        location: "Winterthur, Switzerland",
        date: "27th Jun to 2nd Jul 2021",
    },
    {
        title: "Discourse and Typological Approaches to the Analysis of Attitudinal Copulas",
        authors: ["Anindita Sahoo"],
        conference: "Workshop on 'Discourse and Typological Approaches of Attitudinal Markers: Implications for Intercultural Communication'",
        organizer: "Hong Kong Baptist University",
        location: "Hong Kong",
        date: "15th Jun 2019",
    },
    {
        title: "Conceptualizing Linguistic and Cultural Identities",
        authors: ["Anindita Sahoo"],
        conference: "National Conference on Language, Identity and Society: Centrality of Language in Contemporary Society",
        organizer: "Gautam Buddha University",
        location: "Greater Noida, India",
        date: "30th to 31st Oct 2015",
    },
    {
        title: "Headlines: Same Lines",
        authors: ["Anindita Sahoo"],
        conference: "Free Linguistics Conference 2015",
        organizer: "De La Salle University",
        location: "Manila, Philippines",
        date: "24th to 26th Sep 2015",
    },
    {
        title: "The development of copulas and their functions: A typological perspective",
        authors: ["Foong Ha Yap", "Abhishek Kumar Kashyap", "Mizuho Tamaji", "Anindita Sahoo"],
        conference: "20th Himalayan Languages Symposium (HLS 20)",
        organizer: "Nanyang Technical University",
        location: "Singapore",
        date: "16th to 18th Jul 2014",
    },
    {
        title: "Error, or no error: An analysis",
        authors: ["Anindita Sahoo"],
        conference: "8th Students Conference of Linguistics in India (SCONLI 8)",
        organizer: "Kashmir University",
        location: "Srinagar, India",
        date: "24th to 26th Mar 2014",
    },
    {
        title: "Re-visiting the Principles of Reflexivization: A Study of Reflexives in Khasi",
        authors: ["Anindita Sahoo"],
        conference: "23rd Annual Meeting of the South East Asian Linguistics Society (SEALS 2013)",
        organizer: "Chulalongkorn University",
        location: "Bangkok, Thailand",
        date: "29th to 31st May 2013",
    },
    {
        title: "Scope Patterns in Oriya",
        authors: ["Anindita Sahoo", "Pritha Chandra"],
        conference: "South Asian Languages Analysis Roundtable 29",
        organizer: "CIIL",
        location: "Mysore, India",
        date: "6th to 9th Jan 2011",
    },
    {
        title: "Gradience In Ditransitives and Morphological Specifities: The Case Of Oriya",
        authors: ["Anindita Sahoo", "Pritha Chandra"],
        conference: "All India Conference of Linguists",
        organizer: "Lucknow University",
        location: "Lucknow, India",
        date: "21st Dec 2010",
    },
    {
        title: "Oriya Passives with Ditransitives",
        authors: ["Anindita Sahoo"],
        conference: "Lancaster Post Graduate Conference",
        organizer: "Lancaster University",
        location: "Lancaster, UK",
        date: "5th Jul 2010",
    },
    {
        title: "Yes-no Questions: Probing the Structures of Indian English",
        authors: ["Anindita Sahoo", "Pritha Chandra"],
        conference: "31st All India Conference of Linguistics",
        organizer: "Hyderabad Central University",
        location: "Hyderabad, India",
        date: "15th to 17th Dec 2009",
    },
]